### ISSUE TITLE
Chats no longer persist to the DB

### ISSUE THREAD

**Issue by teksrc** [pszujewski/rephrase-v2.0.0#12]
Hey Peter, at some point with our Rephrase project the chats stopped persisting to our DB, seeing as this is now a main repo on your GitHub, do you have any idea what's occurring. I haven't had a chance to look at the source code in a long time.

I hope you are well and that we can connect sometime and talk about your journey since graduation!

Cheers!

![Screen Shot 2019-04-10 at 2 35 37 PM](https://user-images.githubusercontent.com/12778639/55915244-16621d80-5b9e-11e9-9fbe-208a0b0fbd97.png)

**Comment by teksrc** [comment]
Any thoughts on why this bug exists now @pszujewski @Reyesjunk ?
My guess is that our DB is no longer maintained, but curious.

**Comment by pszujewski** [comment]
Hey @Frankcarvajal good to hear from you. I hope you're well. I'm not sure why it wouldn't work anymore. Probably the mongodb or heroku accounts are technically inactive? There haven't been any code updates since we worked on it initially, so it probably has something to do w/ an account.
